<?php

namespace Yudhi\Apigen\Test;

use Orchestra\Testbench\TestCase as BaseTestCase;
use Yudhi\Apigen\ApiGenBaseServiceProvider;
use Yudhi\Apigen\Core\Controller;

class TestCases extends BaseTestCase
{
    public function getPackageProviders($app): array
    {
        return [
            ApiGenBaseServiceProvider::class,
        ];
    }

    public function getEnvironmentSetUp($app): void
    {
        $curDir = explode('api-generator', __DIR__);
        $curDirSrc = $curDir[0].'api-generator'.DIRECTORY_SEPARATOR.'app'.DIRECTORY_SEPARATOR.'Core'.DIRECTORY_SEPARATOR;
        $curDirStub = $curDir[0].'api-generator'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'stubs'.DIRECTORY_SEPARATOR;
        $app['config']->set('apigen', [
            'abstractControllerName' => Controller::class,
            'rootNamespace' => 'Yudhi\\ApiGen\\App',
            'basePath' => $curDir[0].DIRECTORY_SEPARATOR.'api-generator',
            'appPath' => $curDirSrc,
            'stubPath' => [
                'controller' => '{rootPath}'.DIRECTORY_SEPARATOR.'stubs'.DIRECTORY_SEPARATOR.'controller.stub',
                'entity' => '{rootPath}'.DIRECTORY_SEPARATOR.'stubs'.DIRECTORY_SEPARATOR.'entity.stub',
                'repository' => '{rootPath}'.DIRECTORY_SEPARATOR.'stubs'.DIRECTORY_SEPARATOR.'repository.stub',
                'service' => '{rootPath}'.DIRECTORY_SEPARATOR.'stubs'.DIRECTORY_SEPARATOR.'service.stub',
                'requests' => [
                    'base' => '{rootPath}'.DIRECTORY_SEPARATOR.'stubs'.DIRECTORY_SEPARATOR.'request.base.stub',
                    'create' => '{rootPath}'.DIRECTORY_SEPARATOR.'stubs'.DIRECTORY_SEPARATOR.'request.create.stub',
                    'update' => '{rootPath}'.DIRECTORY_SEPARATOR.'stubs'.DIRECTORY_SEPARATOR.'request.update.stub',
                ],
            ],

        ]);
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
