<?php

namespace Yudhi\Apigen\Test;

use Orchestra\Testbench\TestCase as BaseTestCase;
use Yudhi\Apigen\ApiGenBaseServiceProvider;
use Yudhi\Apigen\Core\Controller;
use Yudhi\Apigen\Helpers\DirHelper;

class TestCases extends BaseTestCase
{
    public function getPackageProviders($app): array
    {
        return [
            ApiGenBaseServiceProvider::class,
        ];
    }

    public function getEnvironmentSetUp($app): void
    {
        $curDir = explode('api-generator', __DIR__);
        $curDirSrc = $curDir[0].'api-generator'.DIRECTORY_SEPARATOR.'app'.DIRECTORY_SEPARATOR.'Core'.DIRECTORY_SEPARATOR;
        $curDirStub = $curDir[0].'api-generator'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'stubs'.DIRECTORY_SEPARATOR;
        $app['config']->set('apigen', [
            'abstractControllerName' => Controller::class,
            'rootNamespace' => 'Yudhi\\ApiGen\\App',
            'basePath'      => $curDir[0].DIRECTORY_SEPARATOR.'api-generator',
            'appPath'       => $curDirSrc,
            'stubPath'      => [
                'controller' => DirHelper::stubDir('controller.stub'),
                'entity'     => DirHelper::stubDir('entity.stub'),
                'repository' => DirHelper::stubDir('repository.stub'),
                'service'    => DirHelper::stubDir('service.stub'),
                'requests'   => [
                    'base'   => DirHelper::stubDir('request.base.stub'),
                    'create' => DirHelper::stubDir('request.create.stub'),
                    'update' => DirHelper::stubDir('request.update.stub'),
                ],
            ],

        ]);
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
